
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: us_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - us_net

  webserver:
    image: nginx:latest
    container_name: us_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - us_net

  db:
    image: mysql:8.0
    container_name: us_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: us_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: us_user
      MYSQL_PASSWORD: us_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - us_net

networks:
  us_net:

volumes:
  dbdata:
